sudo: required
services:
  - docker

language: c

cache: ccache

env:
    matrix:
      - OS=centos DIST=7 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=fedora DIST=24 PACK=rpm
      - OS=fedora DIST=rawhide PACK=rpm
      - OS=ubuntu DIST=wily PACK=deb
      - OS=ubuntu DIST=xenial PACK=deb
      - OS=ubuntu DIST=yakkety PACK=deb
      - OS=debian DIST=stretch PACK=deb

script:
  - git clone https://github.com/zmre/build.git
  - ./build/pack/travis.sh

notifications:
  email: true
  irc: false
